const products=[{name:"Healthy Dog Food",category:"Food",price:2500,icon:"🥣",desc:"Nutritious food for healthy and active dogs."},{name:"Cat Crunch Food",category:"Food",price:1900,icon:"🐟",desc:"Tasty daily food for cats."},{name:"Chew Toy",category:"Toys",price:850,icon:"🦴",desc:"Fun toy for active pets."},{name:"Ball Toy",category:"Toys",price:650,icon:"⚽",desc:"Simple and fun pet play ball."},{name:"Pet Shampoo",category:"Grooming",price:1200,icon:"🧴",desc:"Gentle shampoo for regular grooming."},{name:"Grooming Brush",category:"Grooming",price:950,icon:"🪮",desc:"Brush for keeping fur clean."},{name:"Pet Bed",category:"Bedding",price:4500,icon:"🛏️",desc:"Soft and comfortable pet bed."},{name:"Pet Jacket",category:"Bedding",price:2200,icon:"🧥",desc:"Comfortable apparel for pets."},{name:"Pet Vitamins",category:"Health",price:1800,icon:"💊",desc:"Sample health supplement listing."}];
const animals=[{name:"Buddy",type:"Dog",age:"2 Years",breed:"Labrador",icon:"🐶",desc:"Friendly and playful dog looking for a home."},{name:"Luna",type:"Cat",age:"1 Year",breed:"Persian",icon:"🐱",desc:"Calm cat who loves attention."},{name:"Max",type:"Dog",age:"3 Years",breed:"Beagle",icon:"🐕",desc:"Active and friendly family dog."},{name:"Snowy",type:"Rabbit",age:"8 Months",breed:"White Rabbit",icon:"🐰",desc:"Quiet and gentle rabbit."}];
function startPortal(){let n=userName.value.trim(),r=document.querySelector('input[name=role]:checked')?.value;if(!n){welcomeMessage.textContent="Please enter your name.";return}let x=r==="owner"?"Pet Owner":r==="vet"?"Veterinarian":"Animal Shelter";welcomeMessage.textContent=`Welcome ${n}! You are logged in as ${x}.`;localStorage.setItem("fureverUser",n);tickerText.textContent=`Hello ${n}! Welcome to FurEver Care • They Deserve Forever Love.`}
function savePet(){let n=petName.value.trim();if(!n){petResult.textContent="Please enter pet name.";return}localStorage.setItem("petProfile",JSON.stringify({name:n,species:species.value,breed:breed.value,age:age.value,vaccination:vaccination.value}));petResult.textContent=`Pet profile saved for ${n}.`}
function cart(){return JSON.parse(localStorage.getItem('fureverCart')||'[]')}
function saveCart(c){localStorage.setItem('fureverCart',JSON.stringify(c))}
function addToCart(name){let p=products.find(x=>x.name===name),c=cart(),old=c.find(x=>x.name===name);if(old)old.qty++;else c.push({...p,qty:1});saveCart(c)}
function buyNow(name){addToCart(name);window.location.href='cart.html'}
function displayProducts(){let el=productList;if(!el)return;let a=[...products],s=(searchBox?.value||'').toLowerCase(),c=categoryFilter?.value||'All',o=sortFilter?.value||'default';a=a.filter(p=>(p.name.toLowerCase().includes(s)||p.desc.toLowerCase().includes(s))&&(c==='All'||p.category===c));if(o==='low')a.sort((x,y)=>x.price-y.price);if(o==='high')a.sort((x,y)=>y.price-x.price);el.innerHTML=a.map(p=>`<div class="product-card"><a class="product-link" href="product.html?name=${encodeURIComponent(p.name)}"><div class="product-img">${p.icon}</div><div class="content"><div class="category">${p.category}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="price">PKR ${p.price.toLocaleString()}</div></div></a><div class="product-actions"><a href="product.html?name=${encodeURIComponent(p.name)}">View Details</a><button onclick="buyNow('${p.name.replace(/'/g,"\\'")}')">Buy Now</button></div></div>`).join('')}
function filterAnimals(t){let a=t==='All'?animals:animals.filter(x=>x.type===t);animalList.innerHTML=a.map(x=>`<div class="animal-card"><div class="animal-img">${x.icon}</div><h3>${x.name}</h3><p><b>${x.type}</b> • ${x.age} • ${x.breed}</p><p>${x.desc}</p><a class="animal-button" href="adoption.html?name=${encodeURIComponent(x.name)}">View Pet</a></div>`).join('')}
function submitFeedback(e){e.preventDefault();let d=JSON.parse(localStorage.getItem('fureverFeedback')||'[]');d.push({name:feedbackName.value,email:feedbackEmail.value,text:feedbackText.value,date:new Date().toLocaleString()});localStorage.setItem('fureverFeedback',JSON.stringify(d));feedbackResult.textContent="Thank you! Your feedback has been recorded.";e.target.reset()}
function showTip(t){let e=document.getElementById('tipText');if(e){e.textContent=t;document.getElementById('tipBox').classList.add('show')}}
function updateClock(){let c=document.getElementById('clock');if(c)c.textContent=new Date().toLocaleTimeString()}setInterval(updateClock,1000);updateClock();
function getLocation(){let l=document.getElementById('location');if(!l)return;if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>l.textContent=`${p.coords.latitude.toFixed(2)}, ${p.coords.longitude.toFixed(2)}`,()=>l.textContent="Location unavailable");else l.textContent="Not supported"}
let count=1248;setInterval(()=>{let v=document.getElementById('visitors');if(v){count++;v.textContent=count}},5000);
document.addEventListener('DOMContentLoaded',()=>{displayProducts();filterAnimals('All');getLocation();let s=localStorage.getItem('fureverUser');if(s&&userName){userName.value=s;welcomeMessage.textContent=`Welcome back ${s}!`}});
const careData={
profile:{icon:"🐕",title:"Pet Profile",description:"Keep all your pet's important information in one place. A complete profile makes it easier to manage your pet's daily care and health.",list:["Add your pet's name, breed and age","Keep vaccination information updated","Store important health records","Track your pet's basic information","Keep care details organized"],infoTitle:"Why Pet Profile is Important?",info:[["📋 Complete Information","Keep your pet's important details organized."],["💉 Vaccination Tracking","Keep vaccination information updated."],["❤️ Better Care","Understand your pet's needs more easily."],["📁 Easy Records","Keep important pet information in one place."]],button:"Add My Pet Profile"},
feeding:{icon:"🥣",title:"Feeding Guide",description:"Good nutrition is an important part of keeping your pet happy and healthy. Follow simple feeding habits according to your pet's needs.",list:["Choose food according to your pet's age","Provide fresh drinking water","Maintain regular feeding times","Give suitable portions","Avoid foods that may be harmful to pets"],infoTitle:"Healthy Feeding",info:[["🐶 Puppies","Young pets need appropriate meals for their growth."],["🐕 Adult Dogs","Provide balanced food in suitable portions."],["🐱 Cats","Choose nutritious food designed for cats."],["💧 Fresh Water","Make sure clean water is always available."]],button:"View Feeding Guide"},
grooming:{icon:"🛁",title:"Grooming Videos",description:"Learn simple grooming techniques that can help keep your pet clean, comfortable and looking their best.",list:["Learn basic brushing techniques","Understand safe bathing routines","Learn basic nail care","Keep ears clean","Maintain a healthy coat"],infoTitle:"Grooming Benefits",info:[["✨ Clean Coat","Regular brushing helps keep the coat clean."],["🛁 Bathing","Learn simple and safe bathing routines."],["✂️ Nail Care","Regular nail care keeps pets comfortable."],["❤️ Healthy Routine","Grooming can help you notice changes early."]],button:"Watch Grooming Tips"},
health:{icon:"❤️",title:"Health Tips",description:"Learn simple ways to support your pet's everyday wellness and recognize when professional veterinary advice may be needed.",list:["Keep vaccination records updated","Schedule regular veterinary checkups","Pay attention to changes in behavior","Take care of dental hygiene","Provide exercise and fresh water"],infoTitle:"Pet Wellness",info:[["🩺 Regular Checkups","Routine veterinary care supports your pet's wellness."],["💉 Vaccinations","Keep your pet's vaccination records organized."],["🦷 Dental Care","Good oral hygiene is an important part of pet care."],["🏃 Daily Activity","Regular activity helps pets stay active."]],button:"Read Health Tips"},
training:{icon:"🎓",title:"Training Tips",description:"Build a positive relationship with your pet through simple, consistent and reward-based training techniques.",list:["Start with simple commands","Use positive reinforcement","Keep training sessions short","Reward good behavior","Be patient and consistent"],infoTitle:"Easy Training",info:[["🐾 Basic Commands","Start with simple commands such as sit and stay."],["⭐ Positive Rewards","Reward good behavior to encourage learning."],["⏱️ Short Sessions","Short sessions can help pets stay focused."],["❤️ Patience","Give your pet time to understand new commands."]],button:"Start Training"}
};
function openCareCard(type,card){let d=careData[type];document.querySelectorAll(".care-card").forEach(x=>x.classList.remove("active"));card.classList.add("active");careDetailIcon.innerText=d.icon;careDetailTitle.innerText=d.title;careDetailDescription.innerText=d.description;careDetailList.innerHTML=d.list.map(x=>`<li>${x}</li>`).join('');careInfoTitle.innerText=d.infoTitle;careInfoContent.innerHTML=d.info.map(x=>`<div class="care-info-item"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('');careMainButton.innerText=d.button;careDetails.style.display="block";setTimeout(()=>careDetails.scrollIntoView({behavior:"smooth",block:"start"}),100)}
function closeCareCard(){careDetails.style.display="none";document.querySelectorAll(".care-card").forEach(x=>x.classList.remove("active"))}